Added test cases for the DynamoDb connection and one Categories filter
rackerlabs/atom-hopper pull request #321
Opened 2021-06-16 12:56 UTC by shub6691

These test cases are for the testing purpose.  More test cases need to be added and code refactoring is required.

2021-06-23 14:46 UTC, AJStieren requested changes
There are 2 big ticket items off the top:

* The tests do not pass
* There is an excessive amount of commented/non-functional code

Also the keys shouldn't be populated here.

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/pom.xml
> +
Add a `name` attribute matching the format of the other adapters. Example [link](https://github.com/rackerlabs/atom-hopper/blob/37f01063cec90c54b260e7caefa238f7a62d3a71/adapters/jdbc/pom.xml#L16).

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/main/java/org/atomhopper/dynamodb/adapter/DynamoFeedPublisher.java
> +import java.util.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/main/java/org/atomhopper/dynamodb/adapter/DynamoFeedPublisher.java
> +import com.amazonaws.services.dynamodbv2.document.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/main/java/org/atomhopper/dynamodb/model/PersistedEntry.java
> +import java.util.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/main/java/org/atomhopper/dynamodb/query/SearchToSqlConverter.java
> +import java.util.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/main/java/org/atomhopper/dynamodb/query/SqlBuilder.java
> +public class SqlBuilder {
It is _so_ weird that you can use SQL based queries for DynamoDB as a primary strategy. This isn't a request to chagne it, just a comment on... it's weird.

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/test/java/DynamoDBFeedPublisherTest.java
> +import static org.mockito.Mockito.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/test/java/DynamoDBFeedSourceTest.java
> +import java.util.*;
Make imports explicit

2021-06-23 14:46 UTC, AJStieren commented on adapters/dynamoDB_adapters/src/test/java/DynamoDBFeedSourceTest.java
> +import static org.mockito.Mockito.*;
Make imports explicit

2021-06-23 14:47 UTC, AJStieren commented
This should not be a PR to Master until the adapter feature has been completed

2021-06-29 06:33 UTC, shub6691 commented
Closing the PR and raising the fresh PR with the removal of commented codes

2021-06-29 06:33 UTC, closed without merging